#pragma once
#include <vector>
#include "string.h"
#include "stdlib.h"
#include <glm/glm.hpp>
#include <glm/ext/vector_float3.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/quaternion.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <assimp/Importer.hpp>
#include <assimp/scene.h>
#include <assimp/mesh.h>
#include <assimp/postprocess.h>
#include "3DTypeDefs.h"
#include "vertex.h"
#include <stdexcept>
#include <algorithm>
#include <bitset>
#include "MoxieEvents.h"
#include <cmath>
#include <al.h>
#include <alc.h>
#include "SDL.h"
#include "LogMacros.h"
#include "GLErrorReporting.h"
